In [ ]:
"""
WARNING!!!!
Create a folder named e-commerce and upload the dataset to make this code
works
"""
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import glob
import os
from tabulate import tabulate
import plotly.express as px

"""
Describe table structure
"""
def describe_table(df):
  print(df.info())
  display(df.describe())

"""
Describe how nulls have the table and their percentage
"""
def describe_nulls(df):
  # Count nulls and their representative percentage
  null_counts = df.isnull().sum()
  null_pcts = df.isnull().mean() * 100

  # create a dataframe to create a table
  summary = pd.DataFrame({
      'Columna': null_counts.index,
      'Total Nulos': null_counts.values,
      'Porcentaje (%)': null_pcts.values
  })

  # print data
  print(tabulate(summary, headers='keys', tablefmt='psql', floatfmt=".2f", showindex=False))

"""
Show geolocation data for *.CSV files who have geographic visualization
"""
def show_geolocation(df):
  df_muestra = df.sample(n=1000)
  fig = px.scatter_mapbox(df_muestra, lat="geolocation_lat", lon="geolocation_lng", color="geolocation_city",
                        mapbox_style="carto-positron", zoom=3)
  fig.show()


if __name__ == "__main__":
  path = './e-commerce/'

  all_files = glob.glob(os.path.join(path, "*.csv"))

  for file in all_files:
    df = pd.read_csv(file)

    describe_table(df)

    describe_nulls(df)

    if "Olist_Geolocation_Dataset" in file.title():
      show_geolocation(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

+-------------------------------+---------------+------------------+
| Columna                       |   Total Nulos |   Porcentaje (%) |
|-------------------------------+---------------+------------------|
| order_id                      |             0 |             0.00 |
| customer_id                   |             0 |             0.00 |
| order_status                  |             0 |             0.00 |
| order_purchase_timestamp      |             0 |             0.00 |
| order_approved_at             |           160 |             0.16 |
| order_delivered_carrier_date  |          1783 |             1.79 |
| order_delivered_customer_date |          2965 |             2.98 |
| order_estimated_delivery_date |             0 |             0.00 |
+-------------------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

+--------------------------+---------------+------------------+
| Columna                  |   Total Nulos |   Porcentaje (%) |
|--------------------------+---------------+------------------|
| customer_id              |             0 |             0.00 |
| customer_unique_id       |             0 |             0.00 |
| customer_zip_code_prefix |             0 |             0.00 |
| customer_city            |             0 |             0.00 |
| customer_state           |             0 |             0.00 |
+--------------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

+-----------------------------+---------------+------------------+
| Columna                     |   Total Nulos |   Porcentaje (%) |
|-----------------------------+---------------+------------------|
| geolocation_zip_code_prefix |             0 |             0.00 |
| geolocation_lat             |             0 |             0.00 |
| geolocation_lng             |             0 |             0.00 |
| geolocation_city            |             0 |             0.00 |
| geolocation_state           |             0 |             0.00 |
+-----------------------------+---------------+------------------+

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

+-------------------------+---------------+------------------+
| Columna                 |   Total Nulos |   Porcentaje (%) |
|-------------------------+---------------+------------------|
| review_id               |             0 |             0.00 |
| order_id                |             0 |             0.00 |
| review_score            |             0 |             0.00 |
| review_comment_title    |         87656 |            88.34 |
| review_comment_message  |         58247 |            58.70 |
| review_creation_date    |             0 |             0.00 |
| review_answer_timestamp |             0 |             0.00 |
+-------------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

+---------------------+---------------+------------------+
| Columna             |   Total Nulos |   Porcentaje (%) |
|---------------------+---------------+------------------|
| order_id            |             0 |             0.00 |
| order_item_id       |             0 |             0.00 |
| product_id          |             0 |             0.00 |
| seller_id           |             0 |             0.00 |
| shipping_limit_date |             0 |             0.00 |
| price               |             0 |             0.00 |
| freight_value       |             0 |             0.00 |
+---------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

+----------------------+---------------+------------------+
| Columna              |   Total Nulos |   Porcentaje (%) |
|----------------------+---------------+------------------|
| order_id             |             0 |             0.00 |
| payment_sequential   |             0 |             0.00 |
| payment_type         |             0 |             0.00 |
| payment_installments |             0 |             0.00 |
| payment_value        |             0 |             0.00 |
+----------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

+-------------------------------+---------------+------------------+
| Columna                       |   Total Nulos |   Porcentaje (%) |
|-------------------------------+---------------+------------------|
| product_category_name         |             0 |             0.00 |
| product_category_name_english |             0 |             0.00 |
+-------------------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

+------------------------+---------------+------------------+
| Columna                |   Total Nulos |   Porcentaje (%) |
|------------------------+---------------+------------------|
| seller_id              |             0 |             0.00 |
| seller_zip_code_prefix |             0 |             0.00 |
| seller_city            |             0 |             0.00 |
| seller_state           |             0 |             0.00 |
+------------------------+---------------+------------------+
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

+----------------------------+---------------+------------------+
| Columna                    |   Total Nulos |   Porcentaje (%) |
|----------------------------+---------------+------------------|
| product_id                 |             0 |             0.00 |
| product_category_name      |           610 |             1.85 |
| product_name_lenght        |           610 |             1.85 |
| product_description_lenght |           610 |             1.85 |
| product_photos_qty         |           610 |             1.85 |
| product_weight_g           |             2 |             0.01 |
| product_length_cm          |             2 |             0.01 |
| product_height_cm          |             2 |             0.01 |
| product_width_cm           |             2 |             0.01 |
+----------------------------+---------------+------------------+